import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Mobile from '../Components/Mobile/Mobile'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="flex flex-col flex-nowrap justify-around items-center  min-w-full  ">
        <Mobile/> 
       
      </div>
    </div>
  )
}
